Lots of stuff, hopefully it works

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -90,23 +90,21 @@ jobs:
       machine running in CircleCI to start the OpenShift Cluster, and uses
       various scripts to install the operator, upgrade it, and verify the
       expected functionality.
-    executor: redhat-openshift/machine-for-local-cluster
+    executor: redhat-openshift/default
     steps:
     - checkout
-    - redhat-openshift/create-local-cluster-with-oc:
-        skip-registry-check: true
+    - run:
+        command: echo "${OPENSHIFT4_ETC_HOSTS_ENTRY}" | sudo tee -a /etc/hosts
+        name: Update hosts for test cluster
     - redhat-openshift/login-and-update-kubeconfig:
         insecure-skip-tls-verify: true
-        openshift-platform-version: 3.x
-        server-address: https://127.0.0.1:8443
-        username: system:admin
+        openshift-platform-version: 4.x
+        password: $OPENSHIFT4_PASSWORD
+        server-address: $OPENSHIFT4_CLUSTER_URL
+        username: $OPENSHIFT4_USER
     - run:
         command: |
           set -xeo pipefail
-
-          # CircleCI virtual machine executors come with pyenv pre-installed,
-          # along with python v3.6.5. We can set this as our global python version
-          pyenv global 3.6.5
 
           # Verify that python exists!
           if ! which python > /dev/null; then
@@ -142,7 +140,6 @@ jobs:
         command: |
           set -eo pipefail
 
-          pyenv global 3.6.5
           python -m pip install operator-courier
 
           export QUAY_TOKEN=$(curl -H "Content-Type: application/json" \
@@ -154,31 +151,91 @@ jobs:
           QUAY_NAMESPACE=snyk-runtime
           PACKAGE_NAME=snyk-operator
 
-          $(pyenv which operator-courier) push "${OPERATOR_DIR}" "${QUAY_NAMESPACE}" "${PACKAGE_NAME}" "${OC_VERSION}" "${QUAY_TOKEN}"
+          operator-courier push "${OPERATOR_DIR}" "${QUAY_NAMESPACE}" "${PACKAGE_NAME}" "${OC_VERSION}" "${QUAY_TOKEN}"
+          echo "export QUAY_TOKEN=${QUAY_TOKEN}" >> $BASH_ENV
         name: Push operator to quay
     - run:
         command: |
-          kubectl apply -f ./test/fixtures/operator/olm/crds.yaml
-          kubectl apply -f ./test/fixtures/operator/olm/olm.yaml
-          kubectl apply -f ./test/fixtures/operator/operator-marketplace-deploy
-        name: Install OLM and operator-marketplace
+          set -xeo pipefail
+
+          ns=$(kubectl get ns snyk-monitor --no-headers --output=go-template={{.metadata.name}} 2>/dev/null)
+          if [[ -z "${ns}"" ]]; then
+            echo "snyk-monitor namespace not found, creating..."
+            kubectl create ns snyk-monitor
+          fi
+
+          kubectl create secret generic snyk-monitor -n snyk-monitor --from-literal=integrationId=2eb0b704-de07-4280-bab6-a7911153047b --from-literal=dockercfg.json={}
+        name: Configure snyk-monitor namespace
     - run:
         command: |
           kubectl apply -f ./test/fixtures/operator/operator-source.yaml
           kubectl apply -f ./test/fixtures/operator/installation.yaml
+
+          opsrc=$(kubectl get operatorsource snyk-operator -n openshift-marketplace --no-headers 2>/dev/null | awk '{print $7}')
+          if [[ -z "${opsrc}" || "${opsrc}" == "Failed" ]]; then
+            >&2 echo "failed to deploy operator source resource"
+            exit 1
+          fi
         name: Apply operator installation files
     - run:
-        command: |-
-          cat \<<EOF | kubectl apply -f -
-            apiVersion: charts.helm.k8s.io/v1alpha1
-            kind: SnykMonitor
-            metadata:
-              name: snyk-monitor
-              namespace: snyk-monitor
-            spec:
-              clusterName: TESTING OPERATOR UPGRADE
-          EOF
+        command: |
+          set -o pipefail
+
+          kubectl apply -f ./test/fixtures/operator/test-resource.yaml
+
+          kubectl get pods -n snyk-monitor --no-headers | \
+            grep "snyk-monitor" | \
+            awk 'END { if (NR==0) exit 1; else print $1 }' | \
+            xargs -I{} kubectl wait pod/{} -n snyk-monitor --timeout 60s --for condition=Ready
         name: Deploy snyk-monitor resource
+    - run:
+        command: |
+          set -xeo pipefail
+
+          curl -XDELETE -H "Accept: application/json" -H "Content-Type: application/json" \
+            -H "Authorization: ${QUAY_TOKEN}" "https://quay.io/cnr/api/v1/packages/snyk-runtime/snyk-operator/$OC_VERSION/helm"
+
+          mv ./temp/0.0.0 ./snyk-operator/deploy/olm-catalog/snyk-operator/
+          rm -rf ./snyk-operator/deploy/olm-catalog/snyk-operator/${OC_VERSION}
+
+          LATEST_TAG_WITH_V=`git describe --abbrev=0 --tags ${CIRCLE_SHA1}` && \
+            LATEST_TAG=${LATEST_TAG_WITH_V:1}
+
+          ./scripts/operator/package-operator.sh ${LATEST_TAG} ${LATEST_TAG} ${LATEST_TAG}
+
+          OPERATOR_DIR=./snyk-operator/deploy/olm-catalog/snyk-operator/
+          QUAY_NAMESPACE=snyk-runtime
+          PACKAGE_NAME=snyk-operator
+
+          operator-courier push "${OPERATOR_DIR}" "${QUAY_NAMESPACE}" "${PACKAGE_NAME}" "${LATEST_TAG}" "${QUAY_TOKEN}"
+
+          kubectl delete -f ./test/fixtures/operator/operator-source.yaml
+          kubectl apply -f ./test/fixtures/operator/operator-source.yaml
+
+          VERSION=$(kubectl get pods -n snyk-monitor --no-headers | \
+            grep "snyk-monitor" | \
+            awk 'END { if (NR==0) exit 1; else print $1 }' | \
+            xargs -I{} kubectl get pod {} -n snyk-monitor -o jsonpath={..image} | \
+            awk '{print $1}' | grep -oE "[0-9]{1}\.[0-9]{1,2}\.[0-9]{1,3}$")
+
+          if [[ "${VERSION}" != "${LATEST_TAG}" ]]; then
+            &>2 echo "versions (${VERSION}) does not match expected (${LATEST_TAG})!"
+            exit 1
+          fi
+
+          echo "Update complete!"
+        name: Upgrade snyk-monitor operator
+    - run:
+        command: |2-
+
+          curl -XDELETE -H "Accept: application/json" -H "Content-Type: application/json" \
+            -H "Authorization: ${QUAY_TOKEN}" "https://quay.io/cnr/api/v1/packages/snyk-runtime/snyk-operator/$VERSION/helm"
+
+          kubectl delete -f ./test/fixtures/operator/operator-source.yaml
+          kubectl delete -f ./test/fixtures/operator/installation.yaml
+          kubectl delete -f ./test/fixtures/operator/test-resource.yaml
+          kubectl delete ns snyk-monitor
+        name: Cleanup
     working_directory: ~/kubernetes-monitor
   deploy_dev:
     docker:
