Increase sleep

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -179,13 +179,16 @@ jobs:
           opsrc=$(kubectl get operatorsource snyk-operator -n openshift-marketplace --no-headers 2>/dev/null | awk '{print $9}')
 
           set -e
-          if [[ -z "${opsrc}" || "${opsrc}" == "Failed" ]]; then
-            >&2 echo "failed to deploy operator source resource"
-            exit 1
-          fi
+          while [[ "${opsrc}" != "Succeeded" ]]; do
+            if [[ -z "${opsrc}" || "${opsrc}" == "Failed" ]]; then
+              >&2 echo "failed to deploy operator source resource"
+              exit 1
+            fi
+            opsrc=$(kubectl get operatorsource snyk-operator -n openshift-marketplace --no-headers 2>/dev/null | awk '{print $9}')
+          done
 
           kubectl apply -f ./test/fixtures/operator/installation.yaml
-          sleep 15
+          sleep 60
           kubectl get pods -n snyk-monitor --no-headers | \
             grep "snyk-operator" | \
             awk 'END { if (NR==0) exit 1; else print $1 }' | \
